### ISSUE TITLE
"Run 'terraform get'" on all external modules

### ISSUE THREAD

**Issue by lukvdborne** [VladRassokhin/intellij-hcl#170]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`): RubyMine 2018.2.3
 - [x] intellij-hcl plugin version (`Settings->Plugins`): 0.6.12
 - [x] Terraform version (`terraform -v`): 0.11.8

### Terraform Configuration Files
```hcl
module "vpc" {
  source                            = "terraform-aws-modules/vpc/aws"
  name                              = "${var.customer}-${var.application}-${var.env}-vpc"
  cidr                              = "${var.cidr}"

  azs                               = ["${data.aws_availability_zones.available.names}"]
  private_subnets                   = ["${var.private_subnets}"]
  public_subnets                    = ["${var.public_subnets}"]
  database_subnets                  = ["${var.database_subnets}"]

  enable_nat_gateway                = true
  single_nat_gateway                = true

  tags = {
    Terraform   = true
    Client      = "${var.customer}"
    Application = "${var.application}"
    Environment = "${var.env}"
  }
}

```

### Exception
```text
```

### Expected Behavior
No terraform errors

### Actual Behavior
```Can't locate module locally: No .terraform found under project directory, please run `terraform get` in appropriate place more... (⌘F1)```

### Steps to Reproduce
1. `rm -fr .terraform`
2. `terraform init`
3. open a .tf file that contains a "source" to a module that is loaded from an external source, such as the Terraform registry (see the VPC module) or Git(Hub)
4. `terraform get`
5. goto 3.

**Comment by andreichernov** [comment]
I have the same problem 

> Can't locate module locally

 with IntelliJ IDEA `2018.2.4` and `0.6.12` intellij-hcl plugin

**Comment by hbernier** [comment]
I have the same issue with an intellij ide, `2018.2.4` and `0.6.12`.

- Downgraded to `2018.2.3`, doesn't work.
- Downgraded to `2018.2.2`, doesn't work.
- Downgraded HCL plugin to `0.6.11`, works on `2018.2.3` and `2018.2.4`. Didn't test further.

**Comment by andreibelov** [comment]
I have the same issue with an intellij idea, 2018.1.5 and 0.6.12.

**Comment by matthew16550** [comment]
Using `Ultimate 2018.2.4` and plugin `0.6.12` the problem seems to be the `Module is missing` Inspection does not get re-checked after `terraform get` finishes.

(Note this inspection is not currently visible in the Inspection Profile settings, see #171)

A workaround that works for me is:
1. `terraform get`
1. Comment out the `source` line in the module
1. Uncomment the `source` line in the module

This forces the inspection to be re-checked and then it finds the `.terraform` directory.

**Comment by kevinseelbach** [comment]
> * Downgraded HCL plugin to `0.6.11`, works on `2018.2.3` and `2018.2.4`. Didn't test further.

This also worked for me on version `2018.2.5`.

If anyone working on this plugin or the original developer has time to step in, I think the problem might be somewhere in `src/kotlin/org/intellij/plugins/hcl/terraform/config/model/ModuleDetectionUtil.kt`. Just a guess. Maybe around line 74 where the `getTerraformModulesManifest` function is called.

I'm not a Java developer and don't have much expertise debugging or running Java code, but I poked around in there hoping I could quickly figure out what changed between `0.16.11` and `0.16.12` (I couldn't).

**Comment by jameshueston** [comment]
This is not working for me today with the latest updates avail for Ultimate 2018.2.5 and HCL 0.6.12.
I haven't tested any other version combinations.

**Comment by c33s** [comment]
same problem here with phpstorm 2017.3 and hcl 0.6.12 using my own modules from gitlab. `.terraform` directory is present (ran `terraform init` before)

**Comment by michaelmeelis** [comment]
I would love to see this problem being resolved. The autocomplete solution for modules is ideal! Instead of checking and pasting and running the plugin validates and really helps. Please try and solve this!! Thank you!

**Comment by btorresgil** [comment]
Still seeing this in hcl 0.6.13.  Any thoughts toward a fix?  It is pretty limiting.

**Comment by whiskey** [comment]
> Still seeing this in hcl 0.6.13. Any thoughts toward a fix? It is pretty limiting, had to switch to VSCode for now.

You could download 0.6.11 and stay at that version. Works for me until all is fixed here.

**Comment by c33s** [comment]
confirmed downgrading to 0.6.11 works as workaround.

code like `source = "git::ssh://git@gitlab.com` doesn't lead to a resource being marked for having a syntax error.

**Comment by VladRassokhin** [comment]
Turns out there should be two modules with the same registry source, e.g. `terraform-aws-modules/vpc/aws`. Terraform itself would reuse module though not reporting that into modules.json.

**Comment by deeptechs** [comment]
I encountered this problem while creating Multiple Instances of a Module in PyCharm. I just wrote 2 module with same source (source = "terraform-aws-modules/autoscaling/aws") with different names.

When applying "terraform get" it is downloading the module files but giving error not accepting the 2. one. 
Error: Inspection info: Reports unresolved modules, run `terraform get`

Tried to delete .terraform dir and some stuff but noting helped. 
I downgraded from 0.6.13 to 0.6.11, error gone.

**Comment by VladRassokhin** [comment]
I've added fix for modules with same registry source

**Comment by VladRassokhin** [comment]
Released in 0.6.14

**Comment by deeptechs** [comment]
Thanks @VladRassokhin it is solved.

**Comment by c33s** [comment]
upgraded to 0.6.14 but still have the error.

terrafrom code:
```
module "foo" {
  source = "git::ssh://git@gitlab.com/example/terraform/modules/foo.git?ref=master"
  count = "${terraform.workspace == "production" ? 1 : 0}"
}
```
> Can't locate module locally: Terraform Module 'foo' with source 'git::ssh://git@gitlab.com/example/terraform/modules/foo.git?ref=master' directory not found locally, use 'terraform get` to fetch modules

**Comment by azelezni** [comment]
Any update on this? the problem is still present in 2019.1 and 2018.3.6

**Comment by VladRassokhin** [comment]
@azelezni Thanks for update. Will take a look onto 'attached projects' a bit later.

**Comment by Jamalarm** [comment]
Can confirm the issue still exists in Ultimate 2019.1.3, very annoying.
Picking a module at random from the registry:

```
module "apigw-lambda" {
  source  = "armorfret/apigw-lambda/aws"
  version = "0.0.3"
  # insert the 5 required variables here
}
```

activates the "not found locally" warning, using intentions and running `terraform get` successfully finds and downloads the module but the warning remains and auto-complete is not available in the module.

**Comment by VladRassokhin** [comment]
@Jamalarm Terraform and plugin versions?

**Comment by Jamalarm** [comment]
Plugin: v0.7.3
Terraform: v0.12.2

**Comment by synesisinc** [comment]
I'm having the same problem, not sure if my case is any different, but I've got a module from a tf repo with double-slashes, in this case "fpco/foundation/aws//modules/single-node-asg".

I'm running
PhpStorm: 2019.2.1
Plugin: v0.7.5
Terraform: v0.11.13

**Comment by VladRassokhin** [comment]
@synesisinc cannot reproduce with 0.7.5 on IntelliJ IDEA 2019.2.1
Any chance you have more than one project open in the same window?

**Comment by synesisinc** [comment]
@VladRassokhin no, only one storm window open, no attached projects. I'll see if I can update my TF any without going to v0.12, as we're not ready for that yet

**Comment by dusansusic** [comment]
I have the same issue with:
Intellij:  2019.3.1
Plugin: 0.7.7
Terraform: v0.12.18

**Comment by c33s** [comment]
@VladRassokhin can you please reopen this issue, its still not fixed.

phpstorm: 2019.3.1
plugin: 0.7.7
terraform: v0.11.10

```
module "foo" {
  source = "git::ssh://git@gitlab.com/example/terraform/modules/foo.git?ref=master"
  count = "${terraform.workspace == "production" ? 1 : 0}"
}
```

error message:
```
Can't locate module locally: Terraform Module 'mymodule' with source 'git::ssh://git@gitlab.com/...' directory not found locally, use `terraform get` to fetch modules
```

the main problem now is that the old version 0.6.11 which don't has this problem keeps crashing on php storm 2019.3.1. so the workaround is gone now.

would be awesome if you can fix this problem

**Comment by matschaffer** [comment]
I ran into this on 0.7.7 & terraform 0.12 as well. Then noticed this in the logs

```
2020-01-23 15:20:42,512 [  31127]   WARN - nfig.model.ModuleDetectionUtil - File PsiDirectory:/Users/mat/safecast/infrastructure/terraform/common is not under project root
2020-01-23 15:20:42,512 [  31127]   WARN - nfig.model.ModuleDetectionUtil - No .terraform found under project directory, please run `terraform get` in appropriate place
2020-01-23 15:20:42,512 [  31127]   WARN - nfig.model.ModuleDetectionUtil - Terraform Module 'map_test' with source 'github.com/riboseinc/terraform-aws-s3-cloudfront-website' directory not found locally, use `terraform get` to fetch modules.
```

If I switch around my file paths so that my terraform files are under my project root, things seem to work.

Here's the before/after filesystem tree to hopefully provide better context

Previous structure:
```
./safecast/safecastapi [project root]
./safecast/infrastructure/terraform [imported as module]
```

New structure:
```
./safecast/api [project root]
./safecast/api/safecastapi [ruby module]
./safecast/api/infrastructure [just a directory under "api" project root]
```

**Comment by c33s** [comment]
@matschaffer  thank you very much <3

can confim its all about the path -.-

i use a central folder for all my projects which only contain the `.idea` folder then i remove this directory from the `Directories` section of phpstorm and add my main "content root" manually.

after updating to the latest version of this plugin and opening the project the normal way (with the `.idea` folder in the same directory as the rest of the code) it works.

it would be cool to allow to configure search paths for this plugin

**Comment by solarmosaic-kflorence** [comment]
Same problem here.

```
 Cannot locate module locally: Terraform Module 'iam' with source 's3::https://s3.amazonaws.com/XXX/terraform/terraform-aws-iam/terraform-aws-iam_v1.0.0.zip' directory not found locally, use `terraform get` to fetch modules.
```

`/path/to/the/module/folder/iam` (relative to project root):
```
.
├── .terraform
│   ├── modules
│   │   ├── iam
│   │   │   ├── Makefile
│   │   │   ├── main.tf
│   │   │   ├── modules
│   │   │   │   ├── iam
│   │   │   │   │   ├── .terraform.lock.hcl
│   │   │   │   │   ├── main.tf
│   │   │   │   │   ├── outputs.tf
│   │   │   │   │   └── variables.tf
│   │   │   │   ├── local-data
│   │   │   │   │   └── outputs.tf
│   │   │   │   └── path
│   │   │   │       ├── outputs.tf
│   │   │   │       └── variables.tf
│   │   │   ├── output.tf
│   │   │   ├── policies
│   │   │   │   └── assume-role
│   │   │   │       └── codebuild.json
│   │   │   ├── variables.tf
│   │   │   └── versions.tf
│   │   ├── iam.path.path
│   │   │   ├── go.mod
│   │   │   ├── go.sum
│   │   │   ├── infra
│   │   │   ├── output.tf
│   │   │   ├── readme.md
│   │   │   └── variables.tf
│   │   ├── iam.session
│   │   │   ├── Makefile
│   │   │   ├── main.tf
│   │   │   ├── modules
│   │   │   │   └── local-data
│   │   │   │       └── outputs.tf
│   │   │   ├── outputs.tf
│   │   │   └── versions.tf
│   │   └── modules.json
│   └── providers
│       └── registry.terraform.io
│           └── hashicorp
│               └── aws
│                   └── 3.58.0
│                       └── darwin_amd64
│                           └── terraform-provider-aws_v3.58.0_x5
├── .terraform.lock.hcl
└── main.tf
```

I feel like this worked fine on older versions of this plugin, but it has become flaky lately and now with the latest version I haven't gotten it to work at all yet.

---

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: org.intellij.plugins.hcl (0.7.14), name.kropp.intellij.makefile (212.4746.52), org.toml.lang (0.2.152.4026-212), org.jetbrains.plugins.hocon (2021.1.0), intellij.prettierJS (212.4746.57), Pythonid (212.4746.96), org.jetbrains.plugins.go (212.4746.92), org.intellij.scala (2021.2.15)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by solarmosaic-kflorence** [comment]
@VladRassokhin I'm still having this problem, should I create a new ticket or do you want to re-open this one? Modules seem to resolve fine for the most part in the "main" module directory, but sub-module folders (e.g. `./modules/foo`) do not resolve.

**Comment by VladRassokhin** [comment]
@solarmosaic-kflorence please open new ticket
