### ISSUE TITLE
Better support for TF 0.12 for loops variables

### ISSUE THREAD

**Issue by VladRassokhin** [VladRassokhin/intellij-hcl#208]
* Complex lookups inside templates show as unresolved references. The new template system allows for some very dynamic code which is likely impossible for the plugin to determine, very often though they are highlighted red due to being unresolved. 

![image](https://user-images.githubusercontent.com/305317/58668167-fcd48b00-832f-11e9-9885-28775f191119.png)

_Originally posted by @benosman in https://github.com/VladRassokhin/intellij-hcl/issues/155#issuecomment-497503146_

**Comment by bowczarek** [comment]
Yeah I also noticed that input variables declared as custom types with different attributes cannot be resolved `object({<ATTR NAME> = <TYPE>, ... })`

**Comment by jerrygb** [comment]
Hi,

Just a heads up on `for_each` loop construct within the `dynamic block` also has a similar issue. The plugin does not seem to interpret it as being component of the iterator object.

Ref: https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks

Thank you once again! Let me know if you want me to create a separate issue.

**Comment by VladRassokhin** [comment]
I've fixed all errors on initial screenshot in 0.7.1. Please try it out

**Comment by apenner-epam** [comment]
Hi,
Plugin version - 0.7.1

Issue:
unresolved references in `dynamic block` 
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/38494162/58752007-1b619000-84b0-11e9-833c-ad9b5d82a13d.png">

**Comment by VladRassokhin** [comment]
@apenner-epam Fixed problems shown on your screenshot, will be available in 0.7.2

@jerrygb Problem with 'key' and 'value' is fixed in 0.7.2 (it's the same as above)

>Also, noticed that the repo here does not have v0.7.0 tag. Is that something you plan to checkin?

There's no tag because that 0.7+ is closed-sorced, unless some decisions is made.

**Comment by d-helios** [comment]
Hi,
It resolves value & key attributes, but doesn't resolve object attributes.
```
Plugin version == 0.7.2
IntelliJ Idea == 2019.1.2
```

Example:
```
variable "s3_notification_configuration" {
  description = "s3 notification configuration"
  type = list(object({
    id            = string
    events        = list(string)
    filter_suffix = string
    filter_prefix = string
  }))
  default = []
}


// SQS
resource "aws_s3_bucket_notification" "this" {
  count  = length(var.s3_notification_configuration)
  bucket = aws_s3_bucket.this.id

  dynamic "queue" {
    for_each = var.s3_notification_configuration
    content {
      id            = queue.value.id
      events        = queue.value.events
      filter_suffix = queue.value.filter_suffix == "" ? null : queue.value.filter_suffix
      filter_prefix = queue.value.filter_prefix == "" ? null : queue.value.filter_prefix
      queue_arn = format(
        "arn:aws:sqs:%s:%s:%s",
        data.aws_region.this.name,
        data.aws_caller_identity.this.account_id,
        join("-", [var.name, queue.value.id, var.environment])
      )
    }
  }
}

```

<img width="709" alt="image" src="https://user-images.githubusercontent.com/16616414/58918644-b1591d00-8733-11e9-9578-eae9053f48f0.png">

**Comment by jstewmon** [comment]
Not sure if it is related, but I have a similar issue accessing complex variables with an index:

![image](https://user-images.githubusercontent.com/909418/58918738-2e16d780-86f1-11e9-9180-00a35b7a1b54.png)

**Comment by VladRassokhin** [comment]
@d-helios, @jstewmon Fixed in 0.7.3, will be released shortly

**Comment by jerrygb** [comment]
@VladRassokhin 

Thank you once again for 0.7.3 fixing all the registered 0.12 issues.

I would like to report one very minor formatting issue, with trailing commas for HCL1 interpolation syntax/HCL2 functions.  See screenshot below.

![Screen Shot 2019-06-11 at 6 32 47 AM](https://user-images.githubusercontent.com/1516634/59265162-c0980900-8c12-11e9-8f5e-6d289cc8327a.png)

Functions that can take variable arguments can end with trailing commas according to HCL grammar, I believe. But the plug-in complains the behaviour as an error. See references below.

It should either be a warning formatting or proposed hint to remove the trailing comma, I think. Please correct me if I am wrong.

**Ref:**
https://www.terraform.io/docs/configuration-0-11/interpolation.html#merge-map1-map2-
https://www.terraform.io/docs/configuration/functions.html

**Comment by jstewmon** [comment]
@VladRassokhin I no longer see errors for valid keys, but there's also no error for invalid keys, and there's no completion help. Is that expected?
![image](https://user-images.githubusercontent.com/909418/59292706-30be8300-8c43-11e9-85bc-20c557b1d3d7.png)


Also, I'm seeing errors referring to another resource from within a content block:
![image](https://user-images.githubusercontent.com/909418/59292649-1a182c00-8c43-11e9-8515-43cf046dfd46.png)

**Comment by VladRassokhin** [comment]
@jstewmon 
>but there's also no error for invalid keys, and there's no completion help. Is that expected?

Yes, for now.

>errors referring to another resource from within a content block

Will create separate issue for that.

**Comment by VladRassokhin** [comment]
@jerrygb
Thanks, I've created separate issue.
