### ISSUE TITLE
for_each and each.value properties should be recognized

### ISSUE THREAD

**Issue by eservent** [VladRassokhin/intellij-hcl#267]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```text
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 976M
Cores: 4
Registry: project.tree.structure.show.url=false
Non-Bundled Plugins: com.github.nokia.pyvenv, Git Scope, com.ppolivka.plugin.gitcleaner, com.sburlyaev.terminal.plugin, gr.jchrist.gitextender, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, izhangzhihao.rainbow.brackets, Pythonid, zielu.gittoolbox
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.7.7
 - [x] Terraform version (`terraform -v`)
0.12.10
aws 2.33.0

### Terraform Configuration Files
```hcl
locals {
  dms_source_endpoints_list = {
    accounting : {
      enable : true
      database_name : "database_name"
      server_name : "server_name"
      port : 5432
      engine_name : "postgres"
      username : "username"
      password : "password"
    },
    bank : {
      enable : false
      database_name : "database_name"
      server_name : "server_name"
      port : 5432
      engine_name : "postgres"
      username : "username"
      password : "password"
    },
  }
}

resource "random_string" "endpoint_password" {
  length  = 16
  special = false
}

resource "aws_dms_endpoint" "source_db_endpoints" {
  for_each = {for k, v in local.dms_source_endpoints_list : k => v if v.enable}

  endpoint_type = "source"
  endpoint_id   = replace("dmse-${var.environment}-${var.product_name}-${each.key}_rds_source", "_", "-")
  database_name = each.value.database_name
  server_name   = each.value.server_name
  port          = each.value.port
  engine_name   = each.value.engine_name
  username      = each.value.username
  password      = random_string.endpoint_password.result

  ssl_mode = "require"

  tags = merge(
  {
    "Name" = "dmse-${var.environment}-${var.product_name}-${each.key}_rds_source"
  },
  )
}

```

### Exception
```text
No exception
```

### Expected Behavior
Should recognize, or at least not error, properties inside each.value like each.value.database_name.
Behavior should be same as if "for_each = local.dms_source_endpoints_list", but it defers when we use for expression.

### Actual Behavior
Each property (database_name, port, etc.) appear as an error (like missing property).  

### Steps to Reproduce
Just copy/paste in IntelliJ

**Comment by gleichda** [comment]
Can  still verify this issue even after using 0.7.9 where #261 was fixed.

IDE version
```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to Media Saturn IT-¬Services GmbH / David Gleich
Subscription is active until October 1, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Non-Bundled Plugins: com.intellij.plugins.watcher, org.intellij.plugins.hcl, name.kropp.intellij.makefile, BashSupport, org.jetbrains.plugins.go, org.jetbrains.plugins.ruby
```

HCL Plugin: 0.7.9

Terraform Version: v0.12.24

**Comment by pyrrhicman** [comment]
This bug still exist.

plugin version: 0.7.10

WebStorm 2020.2.3
Build #WS-202.7660.23, built on September 30, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep

![Screenshot 2020-10-26 at 11 53 59](https://user-images.githubusercontent.com/32340808/97158333-f09d6900-1781-11eb-9c2e-b375e274a656.png)

**Comment by salokanto** [comment]
It's still an issue. OSX, plugin 0.7.10 (not updated since the previous post almost a year ago).

<img width="767" alt="Screenshot 2021-07-13 at 10 51 47" src="https://user-images.githubusercontent.com/2944714/125413577-352ba77b-c2b1-4c77-83a4-bc2a76abb974.png">

**Comment by mycarrysun** [comment]
Still an issue for me as well on v0.7.14

**Comment by irrelevanti** [comment]
v0.7.15 confirm the issue is still there
