### ISSUE TITLE
Pressing 'Enter' indents to position 9

### ISSUE THREAD

**Issue by ringods** [VladRassokhin/intellij-hcl#9]
I have a perfectly valid .tf file. Pressing the `Enter` key outside of any resource definition (so, at the root), indents the new line to position 9. This is very annoying, and I don't seem to get rid of it.

I went through the Code style settings in my IntelliJ, but nothing seems to apply or resolve this.

Can you have a look at this?

Context:
* Mac OS X 10.10.5
* IntelliJ Ultimate 14.1.3
* HCL plugin 0.2.7

**Comment by VladRassokhin** [comment]
I'm investigating cause.
Possible workaround is to disable `Settings` -> `Editor` -> `General` -> `Smart Keys` -> `Enter` -> `Smart indent`. Easy way: search for `Smart indent` in `Find Action` feature (`Cmd`+`Shift`+`A`)

**Comment by VladRassokhin** [comment]
I've uploaded version 0.2.8. Bug should be fixed there.

**Comment by ringods** [comment]
@VladRassokhin sorry to say, but the new release doesn't fix it for me. I do not want to disable `Smart indent` as this disables if for all file types.

**Comment by VladRassokhin** [comment]
That's strange. Could you please attach here screenshots of code style settings for `HCL` and `Terraform config` and simple example of file.

**Comment by ringods** [comment]
I exported my `Code style` settings. This file only contains the deviations from the defaults:

```
<code_scheme name="Default (1)">
  <XML>
    <option name="XML_LEGACY_SETTINGS_IMPORTED" value="true" />
  </XML>
  <codeStyleSettings language="ruby">
    <indentOptions>
      <option name="CONTINUATION_INDENT_SIZE" value="2" />
    </indentOptions>
  </codeStyleSettings>
</code_scheme>
```

As you can see, nothing changed from the defaults.

Sample file `vpc.tf` which I use to setup an Amazon Virtual Private Cloud with additional resources. When I press `Enter` in between 2 resource definitions, my cursor jumps to position 9.

```
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
}

# Main VPC
resource "aws_vpc" "rq_vpc" {
  cidr_block = "${var.vpc_cidr}"
  enable_dns_hostnames = true
  tags {
    Name = "rq-vpc-${var.rq_env}"
    Environment = "${var.rq_env}"
  }
}

# Internet gateway for the public subnet
resource "aws_internet_gateway" "rq_public_internet_gateway" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  tags {
    Name = "rq-igw-${var.rq_env}"
    Environment = "${var.rq_env}"
  }
}

# Gateway into the private subnets of the VPC
resource "aws_vpn_gateway" "rq_vpn_private_gw" {
  vpc_id = "${aws_vpc.rq_vpc.id}"

  tags {
    Name = "rq-vgw-${var.rq_env}"
    Environment = "${var.rq_env}"
  }
}

# Gateway from Ringo's network to the Private VPN Gateway
resource "aws_customer_gateway" "rq_customer_gw_ringo" {
  bgp_asn = 60000
  ip_address = "${var.gateway_network_ringo}"
  type = "ipsec.1"
  tags {
    Name = "rq-cgw-ringo-${var.rq_env}"
    Environment = "${var.rq_env}"
  }
}

# Public subnets
resource "aws_subnet" "rq_public_subnet_zone_1" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  cidr_block = "${var.subnet_public_zone1_cidr}"
  availability_zone = "${var.availability_zone_1}"
  map_public_ip_on_launch = true
  depends_on = [
    "aws_internet_gateway.rq_public_internet_gateway"]
  tags {
    Name = "rq-${var.rq_env}-subnet-public-${var.availability_zone_1}"
    Description = "RQ Publicly Routed subnet in Availability Zone ${var.availability_zone_1}"
    Environment = "${var.rq_env}"
  }
}

resource "aws_subnet" "rq_public_subnet_zone_2" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  cidr_block = "${var.subnet_public_zone2_cidr}"
  availability_zone = "${var.availability_zone_2}"
  map_public_ip_on_launch = true
  depends_on = [
    "aws_internet_gateway.rq_public_internet_gateway"]
  tags {
    Name = "rq-${var.rq_env}-subnet-public-${var.availability_zone_2}"
    Description = "RQ Publicly Routed subnet in Availability Zone ${var.availability_zone_2}"
    Environment = "${var.rq_env}"
  }
}

# Private subnets
# Note: db_subnet_group requires at least 2 subnets in 2 separate availability zones
resource "aws_subnet" "rq_private_subnet_zone_1" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  cidr_block = "${var.subnet_private_zone1_cidr}"
  availability_zone = "${var.availability_zone_1}"
  map_public_ip_on_launch = true
  depends_on = [
    "aws_internet_gateway.rq_public_internet_gateway"]
  tags {
    Name = "rq-${var.rq_env}-subnet-private-${var.availability_zone_1}"
    Description = "RQ Privately Routed subnet in Availability Zone ${var.availability_zone_1}"
    Environment = "${var.rq_env}"
  }
}

resource "aws_subnet" "rq_private_subnet_zone_2" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  cidr_block = "${var.subnet_private_zone2_cidr}"
  availability_zone = "${var.availability_zone_2}"
  map_public_ip_on_launch = true
  depends_on = [
    "aws_internet_gateway.rq_public_internet_gateway"]
  tags {
    Name = "rq-${var.rq_env}-subnet-private-${var.availability_zone_2}"
    Description = "RQ Privately Routed subnet in Availability Zone ${var.availability_zone_2}"
    Environment = "${var.rq_env}"
  }
}

# Routing table for public subnets
resource "aws_route_table" "rq_public_subnet_route_table" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  route {
    cidr_block = "${var.routetable_public_cidr}"
    gateway_id = "${aws_internet_gateway.rq_public_internet_gateway.id}"
  }
  tags {
    Name = "rq-${var.rq_env}-routetable-public"
    Description = "RQ Routing Table for publicly routed subnets"
    Environment = "${var.rq_env}"
  }
}

# Routing table for private subnets
resource "aws_route_table" "rq_private_subnet_route_table" {
  vpc_id = "${aws_vpc.rq_vpc.id}"
  route {
    cidr_block = "${var.routetable_network_ringo_cidr}"
    gateway_id = "${aws_vpn_gateway.rq_vpn_private_gw.id}"
  }
  propagating_vgws = [ "${aws_vpn_gateway.rq_vpn_private_gw.id}" ]
  tags {
    Name = "rq-${var.rq_env}-routetable-network-ringo"
    Description = "RQ Routing Table to network Ringo over VPN Gateway"
    Environment = "${var.rq_env}"
  }
}

# Associate the public subnets to the internet routing table
resource "aws_route_table_association" "public_subnet_zone_1_to_internet_routetable" {
  subnet_id = "${aws_subnet.rq_public_subnet_zone_1.id}"
  route_table_id = "${aws_route_table.rq_public_subnet_route_table.id}"
}

resource "aws_route_table_association" "public_subnet_zone_2_to_internet_routetable" {
  subnet_id = "${aws_subnet.rq_public_subnet_zone_2.id}"
  route_table_id = "${aws_route_table.rq_public_subnet_route_table.id}"
}

# Associate the private subnets to the VPN gateway routing table
resource "aws_route_table_association" "private_subnet_zone_1_to_vpn_routetable" {
  subnet_id = "${aws_subnet.rq_private_subnet_zone_1.id}"
  route_table_id = "${aws_route_table.rq_private_subnet_route_table.id}"
}

resource "aws_route_table_association" "private_subnet_zone_2_to_vpn_routetable" {
  subnet_id = "${aws_subnet.rq_private_subnet_zone_2.id}"
  route_table_id = "${aws_route_table.rq_private_subnet_route_table.id}"
}

# Configuration for the VPN connection
resource "aws_vpn_connection" "rq_vpn_network_ringo" {
  vpn_gateway_id = "${aws_vpn_gateway.rq_vpn_private_gw.id}"
  customer_gateway_id = "${aws_customer_gateway.rq_customer_gw_ringo.id}"
  type = "ipsec.1"
  static_routes_only = false
}
```

**Comment by VladRassokhin** [comment]
Please try 0.2.9, now it should be fixed for '.tf' files also (previous fix affected only '.hcl' files)

**Comment by VladRassokhin** [comment]
And thanks for file, don't you mind if i would use it for testing purposes?

**Comment by ringods** [comment]
Tested and verified OK! Thanks.

Go ahead with using the file. I think for testing, it has numerous aspects: multiple resources, dependencies, variables and alike. For the rest, it doesn't contain any real IP addresses, nor credentials, so it's definitely fine.

**Comment by VladRassokhin** [comment]
Ok, thanks.

If you have any feedback/ideas related to this plugin, please share.
